apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: phpimage
        image: vimal13/apache-webserver-php
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: webvol
          mountPath: /var/www/html
      volumes:
      - name: webvol
        persistentVolumeClaim:
          claimName: web1
---


kind: Service
apiVersion: v1
metadata:
  name: hostservice
spec:
  type: NodePort
  selector:
    app: webserver
  ports:
    - nodePort: 30100
      port: 8180
      targetPort: 80
